// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz8SiLzCJ0yLmja7xfnspqfEwEifcvhFw',
    appId: '1:983889081700:web:19f09fb0b1b547d95a7671',
    messagingSenderId: '983889081700',
    projectId: 'belajar-e0d12',
    authDomain: 'belajar-e0d12.firebaseapp.com',
    databaseURL: 'https://belajar-e0d12-default-rtdb.firebaseio.com',
    storageBucket: 'belajar-e0d12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmc4CWVTa_bzgf0shIdEhTFq5YB7ng17I',
    appId: '1:983889081700:android:da9cede3341152465a7671',
    messagingSenderId: '983889081700',
    projectId: 'belajar-e0d12',
    databaseURL: 'https://belajar-e0d12-default-rtdb.firebaseio.com',
    storageBucket: 'belajar-e0d12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvzynEr9vuycTlBTRz_4GXQTJ6mRUul6s',
    appId: '1:983889081700:ios:9bb9a4e37c4334a35a7671',
    messagingSenderId: '983889081700',
    projectId: 'belajar-e0d12',
    databaseURL: 'https://belajar-e0d12-default-rtdb.firebaseio.com',
    storageBucket: 'belajar-e0d12.firebasestorage.app',
    iosBundleId: 'com.example.belajar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvzynEr9vuycTlBTRz_4GXQTJ6mRUul6s',
    appId: '1:983889081700:ios:9bb9a4e37c4334a35a7671',
    messagingSenderId: '983889081700',
    projectId: 'belajar-e0d12',
    databaseURL: 'https://belajar-e0d12-default-rtdb.firebaseio.com',
    storageBucket: 'belajar-e0d12.firebasestorage.app',
    iosBundleId: 'com.example.belajar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz8SiLzCJ0yLmja7xfnspqfEwEifcvhFw',
    appId: '1:983889081700:web:aef0602cad9fbc925a7671',
    messagingSenderId: '983889081700',
    projectId: 'belajar-e0d12',
    authDomain: 'belajar-e0d12.firebaseapp.com',
    databaseURL: 'https://belajar-e0d12-default-rtdb.firebaseio.com',
    storageBucket: 'belajar-e0d12.firebasestorage.app',
  );
}
