// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqjpMzEDcZ4v1nGlvSasp2TNZeO1VI8eY',
    appId: '1:78645284128:web:74f7bc07f9c369694ddb45',
    messagingSenderId: '78645284128',
    projectId: 'notes-9d0f2',
    authDomain: 'notes-9d0f2.firebaseapp.com',
    storageBucket: 'notes-9d0f2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjmMPimHd5uPHyLE5qb_fQdt3mQmBu7lA',
    appId: '1:78645284128:android:558bdafb04d29e754ddb45',
    messagingSenderId: '78645284128',
    projectId: 'notes-9d0f2',
    storageBucket: 'notes-9d0f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWwEcbkbaFhcaSnSSAobDsqykohWibNe4',
    appId: '1:78645284128:ios:ae0fceeb0f402b3c4ddb45',
    messagingSenderId: '78645284128',
    projectId: 'notes-9d0f2',
    storageBucket: 'notes-9d0f2.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWwEcbkbaFhcaSnSSAobDsqykohWibNe4',
    appId: '1:78645284128:ios:ae0fceeb0f402b3c4ddb45',
    messagingSenderId: '78645284128',
    projectId: 'notes-9d0f2',
    storageBucket: 'notes-9d0f2.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqjpMzEDcZ4v1nGlvSasp2TNZeO1VI8eY',
    appId: '1:78645284128:web:050d776c942b77014ddb45',
    messagingSenderId: '78645284128',
    projectId: 'notes-9d0f2',
    authDomain: 'notes-9d0f2.firebaseapp.com',
    storageBucket: 'notes-9d0f2.firebasestorage.app',
  );
}
