// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5d8xKT8UvCEGF3qa7BpuBNz8RVfQDZNE',
    appId: '1:696231418303:web:6b45ae9cdf6ee5123c690a',
    messagingSenderId: '696231418303',
    projectId: 'daftarbelanja-edacf',
    authDomain: 'daftarbelanja-edacf.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-edacf-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-edacf.firebasestorage.app',
    measurementId: 'G-MW7QH13VYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgAUs-EbT1NxZkatx4-niR8ZMdb4bizSA',
    appId: '1:696231418303:android:5156479c36f557223c690a',
    messagingSenderId: '696231418303',
    projectId: 'daftarbelanja-edacf',
    databaseURL: 'https://daftarbelanja-edacf-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-edacf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFPPLvX8JwMsc3J5wxZl2RvJjQg-h8X-g',
    appId: '1:696231418303:ios:cc9f0d05a460da323c690a',
    messagingSenderId: '696231418303',
    projectId: 'daftarbelanja-edacf',
    databaseURL: 'https://daftarbelanja-edacf-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-edacf.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFPPLvX8JwMsc3J5wxZl2RvJjQg-h8X-g',
    appId: '1:696231418303:ios:cc9f0d05a460da323c690a',
    messagingSenderId: '696231418303',
    projectId: 'daftarbelanja-edacf',
    databaseURL: 'https://daftarbelanja-edacf-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-edacf.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5d8xKT8UvCEGF3qa7BpuBNz8RVfQDZNE',
    appId: '1:696231418303:web:c61bc9757fecbb173c690a',
    messagingSenderId: '696231418303',
    projectId: 'daftarbelanja-edacf',
    authDomain: 'daftarbelanja-edacf.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-edacf-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-edacf.firebasestorage.app',
    measurementId: 'G-NWZNB367KK',
  );
}
