// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByF8vtAX4xMOhsoOWs04EdNRA5hNrbRZI',
    appId: '1:573460880757:web:7e43b4d8f3bb010f11473c',
    messagingSenderId: '573460880757',
    projectId: 'cloud-message-81615',
    authDomain: 'cloud-message-81615.firebaseapp.com',
    storageBucket: 'cloud-message-81615.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA11GjSzUbpG1ukZMLbI1J15o20KiB85Vs',
    appId: '1:573460880757:android:e701a9013b68dea011473c',
    messagingSenderId: '573460880757',
    projectId: 'cloud-message-81615',
    storageBucket: 'cloud-message-81615.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByqvf9EslRE0zsh1NWg77aejKnwQhtsGQ',
    appId: '1:573460880757:ios:ecd1ac2c0c51a9b211473c',
    messagingSenderId: '573460880757',
    projectId: 'cloud-message-81615',
    storageBucket: 'cloud-message-81615.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByqvf9EslRE0zsh1NWg77aejKnwQhtsGQ',
    appId: '1:573460880757:ios:ecd1ac2c0c51a9b211473c',
    messagingSenderId: '573460880757',
    projectId: 'cloud-message-81615',
    storageBucket: 'cloud-message-81615.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByF8vtAX4xMOhsoOWs04EdNRA5hNrbRZI',
    appId: '1:573460880757:web:60cf2106fde6209a11473c',
    messagingSenderId: '573460880757',
    projectId: 'cloud-message-81615',
    authDomain: 'cloud-message-81615.firebaseapp.com',
    storageBucket: 'cloud-message-81615.firebasestorage.app',
  );

}