// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGnCE_QPNP_2txFutTClwzIMPpHagDv4g',
    appId: '1:704103030534:web:acc0f946036b3050ee0887',
    messagingSenderId: '704103030534',
    projectId: 'mdpgold-83d25',
    authDomain: 'mdpgold-83d25.firebaseapp.com',
    databaseURL: 'https://mdpgold-83d25-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-83d25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk8JrRJ3t2N4A5fH1eJ0Yxn1pdH361hiY',
    appId: '1:704103030534:android:d0c5bce40eead52fee0887',
    messagingSenderId: '704103030534',
    projectId: 'mdpgold-83d25',
    databaseURL: 'https://mdpgold-83d25-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-83d25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRxNSXbAJvlhiJ6b4nGHnmaY3DFa1-ZiE',
    appId: '1:704103030534:ios:72350a7021c768f3ee0887',
    messagingSenderId: '704103030534',
    projectId: 'mdpgold-83d25',
    databaseURL: 'https://mdpgold-83d25-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-83d25.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRxNSXbAJvlhiJ6b4nGHnmaY3DFa1-ZiE',
    appId: '1:704103030534:ios:72350a7021c768f3ee0887',
    messagingSenderId: '704103030534',
    projectId: 'mdpgold-83d25',
    databaseURL: 'https://mdpgold-83d25-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-83d25.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGnCE_QPNP_2txFutTClwzIMPpHagDv4g',
    appId: '1:704103030534:web:851121db0f93c78fee0887',
    messagingSenderId: '704103030534',
    projectId: 'mdpgold-83d25',
    authDomain: 'mdpgold-83d25.firebaseapp.com',
    databaseURL: 'https://mdpgold-83d25-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-83d25.firebasestorage.app',
  );
}
